pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository from GitHub
                git 'https://github.com/jaafardialloo/LifeSkillsBackEnd.git'
            }
        }

        stage('Build') {
            steps {
                // Run Gradle build
                sh 'gradle clean build'
            }
        }

        stage('Deploy') {
            steps {
                // Perform deployment steps, e.g., deploy to a server
                sh 'gradle deploy'
            }
        }
    }
}